// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	AuthorizationScopes = "Authorization.Scopes"
)

// Defines values for Colours.
const (
	Amber      Colours = "amber"
	Blue       Colours = "blue"
	Chartreuse Colours = "chartreuse"
	Green      Colours = "green"
	Magenta    Colours = "magenta"
	Orange     Colours = "orange"
	Purple     Colours = "purple"
	Red        Colours = "red"
	Teal       Colours = "teal"
	Vermillion Colours = "vermillion"
	Violet     Colours = "violet"
	Yellow     Colours = "yellow"
)

// Colours defines model for Colours.
type Colours string

// IncomingCalendar defines model for IncomingCalendar.
type IncomingCalendar struct {
	Color *Colours `json:"color,omitempty"`
	Name  string   `json:"name"`
}

// IncomingEvent defines model for IncomingEvent.
type IncomingEvent struct {
	AllDay    bool      `json:"allDay"`
	EndDate   time.Time `json:"endDate"`
	StartDate time.Time `json:"startDate"`
	Title     string    `json:"title"`
}

// OutgoingCalendar defines model for OutgoingCalendar.
type OutgoingCalendar struct {
	Color *Colours           `json:"color,omitempty"`
	Id    openapi_types.UUID `json:"id"`
	Name  string             `json:"name"`
}

// OutgoingEvent defines model for OutgoingEvent.
type OutgoingEvent struct {
	AllDay     bool               `json:"allDay"`
	CalendarId openapi_types.UUID `json:"calendarId"`
	EndDate    time.Time          `json:"endDate"`
	Id         openapi_types.UUID `json:"id"`
	StartDate  time.Time          `json:"startDate"`
	Title      string             `json:"title"`
}

// CalendarId defines model for CalendarId.
type CalendarId = openapi_types.UUID

// EventId defines model for EventId.
type EventId = openapi_types.UUID

// GetCalendar defines model for GetCalendar.
type GetCalendar = OutgoingCalendar

// GetCalendars defines model for GetCalendars.
type GetCalendars = []OutgoingCalendar

// GetEvent defines model for GetEvent.
type GetEvent = OutgoingEvent

// GetEvents defines model for GetEvents.
type GetEvents = []OutgoingEvent

// PostCalendar defines model for PostCalendar.
type PostCalendar = OutgoingCalendar

// PostEvent defines model for PostEvent.
type PostEvent = OutgoingEvent

// PutCalendar defines model for PutCalendar.
type PutCalendar = OutgoingCalendar

// PutEvent defines model for PutEvent.
type PutEvent = OutgoingEvent

// PostCalendarJSONRequestBody defines body for PostCalendar for application/json ContentType.
type PostCalendarJSONRequestBody = IncomingCalendar

// PutCalendarJSONRequestBody defines body for PutCalendar for application/json ContentType.
type PutCalendarJSONRequestBody = IncomingCalendar

// PostEventJSONRequestBody defines body for PostEvent for application/json ContentType.
type PostEventJSONRequestBody = IncomingEvent

// PutEventJSONRequestBody defines body for PutEvent for application/json ContentType.
type PutEventJSONRequestBody = IncomingEvent

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get all calendars
	// (GET /calendars)
	GetCalendars(w http.ResponseWriter, r *http.Request)
	// Create a new calendar
	// (POST /calendars)
	PostCalendar(w http.ResponseWriter, r *http.Request)
	// Delete a calendar
	// (DELETE /calendars/{calendarId})
	DeleteCalendar(w http.ResponseWriter, r *http.Request, calendarId CalendarId)
	// Get a calendar
	// (GET /calendars/{calendarId})
	GetCalendar(w http.ResponseWriter, r *http.Request, calendarId CalendarId)
	// Update an existing calendar
	// (PUT /calendars/{calendarId})
	PutCalendar(w http.ResponseWriter, r *http.Request, calendarId CalendarId)
	// Get all events of a calendar
	// (GET /calendars/{calendarId}/events)
	GetEventsForCalendar(w http.ResponseWriter, r *http.Request, calendarId CalendarId)
	// Create an event for a calendar
	// (POST /calendars/{calendarId}/events)
	PostEvent(w http.ResponseWriter, r *http.Request, calendarId CalendarId)
	// Delete an event
	// (DELETE /calendars/{calendarId}/events/{eventId})
	DeleteEvent(w http.ResponseWriter, r *http.Request, calendarId CalendarId, eventId EventId)
	// Get an event
	// (GET /calendars/{calendarId}/events/{eventId})
	GetEvent(w http.ResponseWriter, r *http.Request, calendarId CalendarId, eventId EventId)
	// Update an existing event
	// (PUT /calendars/{calendarId}/events/{eventId})
	PutEvent(w http.ResponseWriter, r *http.Request, calendarId CalendarId, eventId EventId)
	// Get all events
	// (GET /events)
	GetEvents(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get all calendars
// (GET /calendars)
func (_ Unimplemented) GetCalendars(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new calendar
// (POST /calendars)
func (_ Unimplemented) PostCalendar(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a calendar
// (DELETE /calendars/{calendarId})
func (_ Unimplemented) DeleteCalendar(w http.ResponseWriter, r *http.Request, calendarId CalendarId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a calendar
// (GET /calendars/{calendarId})
func (_ Unimplemented) GetCalendar(w http.ResponseWriter, r *http.Request, calendarId CalendarId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update an existing calendar
// (PUT /calendars/{calendarId})
func (_ Unimplemented) PutCalendar(w http.ResponseWriter, r *http.Request, calendarId CalendarId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get all events of a calendar
// (GET /calendars/{calendarId}/events)
func (_ Unimplemented) GetEventsForCalendar(w http.ResponseWriter, r *http.Request, calendarId CalendarId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create an event for a calendar
// (POST /calendars/{calendarId}/events)
func (_ Unimplemented) PostEvent(w http.ResponseWriter, r *http.Request, calendarId CalendarId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete an event
// (DELETE /calendars/{calendarId}/events/{eventId})
func (_ Unimplemented) DeleteEvent(w http.ResponseWriter, r *http.Request, calendarId CalendarId, eventId EventId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get an event
// (GET /calendars/{calendarId}/events/{eventId})
func (_ Unimplemented) GetEvent(w http.ResponseWriter, r *http.Request, calendarId CalendarId, eventId EventId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update an existing event
// (PUT /calendars/{calendarId}/events/{eventId})
func (_ Unimplemented) PutEvent(w http.ResponseWriter, r *http.Request, calendarId CalendarId, eventId EventId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get all events
// (GET /events)
func (_ Unimplemented) GetEvents(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetCalendars operation middleware
func (siw *ServerInterfaceWrapper) GetCalendars(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AuthorizationScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCalendars(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostCalendar operation middleware
func (siw *ServerInterfaceWrapper) PostCalendar(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AuthorizationScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostCalendar(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCalendar operation middleware
func (siw *ServerInterfaceWrapper) DeleteCalendar(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "calendarId" -------------
	var calendarId CalendarId

	err = runtime.BindStyledParameterWithOptions("simple", "calendarId", chi.URLParam(r, "calendarId"), &calendarId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "calendarId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AuthorizationScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCalendar(w, r, calendarId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCalendar operation middleware
func (siw *ServerInterfaceWrapper) GetCalendar(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "calendarId" -------------
	var calendarId CalendarId

	err = runtime.BindStyledParameterWithOptions("simple", "calendarId", chi.URLParam(r, "calendarId"), &calendarId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "calendarId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AuthorizationScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCalendar(w, r, calendarId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutCalendar operation middleware
func (siw *ServerInterfaceWrapper) PutCalendar(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "calendarId" -------------
	var calendarId CalendarId

	err = runtime.BindStyledParameterWithOptions("simple", "calendarId", chi.URLParam(r, "calendarId"), &calendarId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "calendarId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AuthorizationScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutCalendar(w, r, calendarId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEventsForCalendar operation middleware
func (siw *ServerInterfaceWrapper) GetEventsForCalendar(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "calendarId" -------------
	var calendarId CalendarId

	err = runtime.BindStyledParameterWithOptions("simple", "calendarId", chi.URLParam(r, "calendarId"), &calendarId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "calendarId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AuthorizationScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEventsForCalendar(w, r, calendarId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostEvent operation middleware
func (siw *ServerInterfaceWrapper) PostEvent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "calendarId" -------------
	var calendarId CalendarId

	err = runtime.BindStyledParameterWithOptions("simple", "calendarId", chi.URLParam(r, "calendarId"), &calendarId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "calendarId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AuthorizationScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostEvent(w, r, calendarId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteEvent operation middleware
func (siw *ServerInterfaceWrapper) DeleteEvent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "calendarId" -------------
	var calendarId CalendarId

	err = runtime.BindStyledParameterWithOptions("simple", "calendarId", chi.URLParam(r, "calendarId"), &calendarId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "calendarId", Err: err})
		return
	}

	// ------------- Path parameter "eventId" -------------
	var eventId EventId

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", chi.URLParam(r, "eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AuthorizationScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteEvent(w, r, calendarId, eventId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEvent operation middleware
func (siw *ServerInterfaceWrapper) GetEvent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "calendarId" -------------
	var calendarId CalendarId

	err = runtime.BindStyledParameterWithOptions("simple", "calendarId", chi.URLParam(r, "calendarId"), &calendarId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "calendarId", Err: err})
		return
	}

	// ------------- Path parameter "eventId" -------------
	var eventId EventId

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", chi.URLParam(r, "eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AuthorizationScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEvent(w, r, calendarId, eventId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutEvent operation middleware
func (siw *ServerInterfaceWrapper) PutEvent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "calendarId" -------------
	var calendarId CalendarId

	err = runtime.BindStyledParameterWithOptions("simple", "calendarId", chi.URLParam(r, "calendarId"), &calendarId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "calendarId", Err: err})
		return
	}

	// ------------- Path parameter "eventId" -------------
	var eventId EventId

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", chi.URLParam(r, "eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AuthorizationScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutEvent(w, r, calendarId, eventId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEvents operation middleware
func (siw *ServerInterfaceWrapper) GetEvents(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AuthorizationScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEvents(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/calendars", wrapper.GetCalendars)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/calendars", wrapper.PostCalendar)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/calendars/{calendarId}", wrapper.DeleteCalendar)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/calendars/{calendarId}", wrapper.GetCalendar)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/calendars/{calendarId}", wrapper.PutCalendar)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/calendars/{calendarId}/events", wrapper.GetEventsForCalendar)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/calendars/{calendarId}/events", wrapper.PostEvent)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/calendars/{calendarId}/events/{eventId}", wrapper.DeleteEvent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/calendars/{calendarId}/events/{eventId}", wrapper.GetEvent)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/calendars/{calendarId}/events/{eventId}", wrapper.PutEvent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/events", wrapper.GetEvents)
	})

	return r
}
